name = "pify"
target = "javascript"
version = "0.4.0"
description = "pify: some helpers to use gleam in your shopify project. for now, only for javascript"
licences = ["Apache-2.0"]
repository = { type = "github", user = "poldo11", repo = "pify" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.2.0 and < 5.0.0"
gleam_fetch = ">= 1.3.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
snag = ">= 1.1.0 and < 2.0.0"
wisp = ">= 2.0.0 and < 3.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
lustre = ">= 5.3.5 and < 6.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
