name = "pify"
version = "0.2.0"
description = "pify: some helpers to use gleam in your shopify project."
licences = ["Apache-2.0"]
repository = { type = "github", user = "poldo11", repo = "pify" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
gleam_http = ">= 4.2.0 and < 5.0.0"
gleam_httpc = ">= 5.0.0 and < 6.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
snag = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
